FROM node:14

ENV MONGO_DB_USERNAME=admin \
    MONGO_DB_PWD=password // artifacts here or in docker-compose file

WORKDIR /app

COPY package.json .

RUN npm install #(install all dependencies)

COPY . . #(copy from dockerfile location to WORKDIR /app)

EXPOSE 3000

CMD [“node”, “app.js”] // execute as an entrypoint, but entrypoint will override
