FROM  --platform=arm64

WORKDIR /opt/homebrew/etc/nginx
#/opt/homebrew/var/www/index.html

MKDIR /testdir

RUN sudo sysctl -w net.inet.ip.ttl=65

RUN pip3 install psycopg2-binary

RUN which pg_config #(/opt/homebrew/bin/pg_config)

RUN which openssl #(/usr/bin/openssl)

CMD ["echo", "hello"]
