database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    command: --init-file /data/application/mysql_insert.sql
    volumes:
        - ./init.sql:/data/application/mysql_insert.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
