stages:
    - build
    - test
    - deploy
    
.build website:
    image: node:16-alpine
    stages: build
    script:
        - yarn install
        - yarn init
        - yarn test
        - yarn buoild
    artifacts:
        paths:
            - build
       
.test website:
    image: node:16-alpine
    stages: test
    script:
        - yarn global add serve
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"
        
 deploy to s3:
      stage: deploy
      image:
          name: amazon/aws-cli:2.4.11
          entrypoint: ["""]
      rules:
          - if: ... == main
      script:
          - aws -- version
          - echo "Hello S3" > test.txt
          # - aws s3 cp test.txt s3://vmorozovintbilisi.s3-website-us-east-1.amazonaws.com/test.txt
          - aws s3 cp test.txt s3://$AWS_S3_BUCKET/test.txt
          
