default:
    image: docker:stable
    tags: 
        - ubuntu

variables:
    CI_DOCKER_REPO: registry.gitlab.com/noshavenovemba/pushdockerfile/myimage:1.1.0

stages:
    - build docker image

before_script:
    - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build_step_1:
    stage: build docker image
    script:
        - docker build -t $CI_DOCKER_REPO .
        - docker push $CI_DOCKER_REPO
