image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - deploy

staging:
    stage: deploy
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=heroku-gitlab-vadim-test --api-key=$HEROKU_STAGING_API_KEY
    only:
        - staging
